name="Stolen Sword v1.0"

[store]
id="com.github.adbenitez.stolensword"
version_name=1.0
version_code=1
author="adbenitez"
author_email="adbenitez@nauta.cu"
description="A one finger action platform game"